/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'catalog-items': CatalogItem;
    inquiries: Inquiry;
    'email-logs': EmailLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'catalog-items': CatalogItemsSelect<false> | CatalogItemsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'email-logs': EmailLogsSelect<false> | EmailLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      syncCatalog: TaskSyncCatalog;
      processInquiry: TaskProcessInquiry;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  /**
   * What this file is, for filtering in the admin.
   */
  kind?: ('reference' | 'quote' | 'mockup') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-items".
 */
export interface CatalogItem {
  id: number;
  /**
   * DK ItemCode / vörunúmer, stored lowercase as in DK (matched case-insensitively).
   */
  itemCode: string;
  /**
   * DK internal RecordID.
   */
  recordId?: number | null;
  description?: string | null;
  description2?: string | null;
  unitCode?: string | null;
  group?: string | null;
  /**
   * Net unit price.
   */
  unitPrice1?: number | null;
  /**
   * VAT-inclusive unit price — the price quotes use.
   */
  unitPrice1WithTax?: number | null;
  taxPercent?: number | null;
  /**
   * Currency of the prices.
   */
  currencyCode?: string | null;
  inactive?: boolean | null;
  showItemInWebShop?: boolean | null;
  /**
   * DK RecordModified — when the product was last edited in DK.
   */
  recordModified?: string | null;
  /**
   * When DK data last changed this row.
   */
  lastSyncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  /**
   * Auto-filled from the customer name + product for readability.
   */
  title?: string | null;
  status?: ('received' | 'processing' | 'quoted' | 'emailed' | 'accepting' | 'accepted' | 'failed') | null;
  /**
   * When the inquiry was accepted.
   */
  acceptedAt?: string | null;
  /**
   * Admin who accepted the inquiry.
   */
  acceptedBy?: (number | null) | User;
  customer?: {
    firstName?: string | null;
    lastName?: string | null;
    /**
     * Icelandic national ID (Kt.).
     */
    kennitala?: string | null;
    /**
     * Heimili.
     */
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  deceased?: {
    firstName?: string | null;
    lastName?: string | null;
    /**
     * As submitted (free text / date).
     */
    bornDate?: string | null;
    /**
     * As submitted (free text / date).
     */
    diedDate?: string | null;
  };
  /**
   * Selections from the order template (Icelandic values).
   */
  options?: {
    /**
     * Font (Letur list).
     */
    letur?: string | null;
    /**
     * Lettering colour (Litur list).
     */
    litur?: string | null;
    /**
     * Stone colour code (Glitir list: SB, BG, …).
     */
    stoneColor?: string | null;
    /**
     * Kirkjugarður.
     */
    cemetery?: string | null;
    /**
     * Afhending.
     */
    delivery?: string | null;
    /**
     * Áletrun price per character (260/1070/1250/1490).
     */
    perCharPrice?: number | null;
    /**
     * Sölumaður.
     */
    solumadur?: string | null;
    /**
     * Athugasemdir.
     */
    comments?: string | null;
    /**
     * Blómarammi price, if chosen.
     */
    blomarammiVerd?: number | null;
    /**
     * Uppsetning (installation) price, if chosen.
     */
    uppsetningVerd?: number | null;
    /**
     * Discount amount (entered as negative in the sheet).
     */
    afslattur?: number | null;
  };
  wantedProduct: {
    /**
     * DK ItemCode the customer chose (from WordPress).
     */
    itemCode: string;
    catalogItem?: (number | null) | CatalogItem;
    resolvedDescription?: string | null;
    resolvedUnitPrice?: number | null;
  };
  inscriptionLines?:
    | {
        line?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add-on codes selected by the customer; type decides the template section.
   */
  addons?:
    | {
        type?: ('kross' | 'luktVasi' | 'fugl' | 'mynd' | 'rammi' | 'annad') | null;
        code: string;
        label?: string | null;
        qty?: number | null;
        id?: string | null;
      }[]
    | null;
  referenceImages?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * The generated .xlsx quote.
   */
  generatedQuote?: (number | null) | Media;
  /**
   * Added when the designer returns a mockup.
   */
  designerMockup?: (number | null) | Media;
  /**
   * Original webhook body, kept for audit / replay.
   */
  rawPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Last processing error, if any.
   */
  processingError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every email the middleware sent (or failed to send), with the attached quote.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs".
 */
export interface EmailLog {
  id: number;
  /**
   * Auto-filled: email type + client name + inquiry id.
   */
  title?: string | null;
  emailType: 'designer-brief' | 'sales-quote';
  status: 'sent' | 'failed';
  sentAt?: string | null;
  /**
   * Client name and surname as submitted on the WordPress form.
   */
  clientName?: string | null;
  /**
   * Recipient address.
   */
  to?: string | null;
  subject?: string | null;
  /**
   * The inquiry this email was sent for.
   */
  inquiry?: (number | null) | Inquiry;
  /**
   * The generated .xlsx quote attached to this email (sales quote only).
   */
  attachment?: (number | null) | Media;
  /**
   * The HTML body as sent.
   */
  html?: string | null;
  /**
   * Send error, if the email failed.
   */
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'syncCatalog' | 'processInquiry';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'syncCatalog' | 'processInquiry') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'catalog-items';
        value: number | CatalogItem;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'email-logs';
        value: number | EmailLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-items_select".
 */
export interface CatalogItemsSelect<T extends boolean = true> {
  itemCode?: T;
  recordId?: T;
  description?: T;
  description2?: T;
  unitCode?: T;
  group?: T;
  unitPrice1?: T;
  unitPrice1WithTax?: T;
  taxPercent?: T;
  currencyCode?: T;
  inactive?: T;
  showItemInWebShop?: T;
  recordModified?: T;
  lastSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  acceptedAt?: T;
  acceptedBy?: T;
  customer?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        kennitala?: T;
        address?: T;
        phone?: T;
        email?: T;
      };
  deceased?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        bornDate?: T;
        diedDate?: T;
      };
  options?:
    | T
    | {
        letur?: T;
        litur?: T;
        stoneColor?: T;
        cemetery?: T;
        delivery?: T;
        perCharPrice?: T;
        solumadur?: T;
        comments?: T;
        blomarammiVerd?: T;
        uppsetningVerd?: T;
        afslattur?: T;
      };
  wantedProduct?:
    | T
    | {
        itemCode?: T;
        catalogItem?: T;
        resolvedDescription?: T;
        resolvedUnitPrice?: T;
      };
  inscriptionLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  addons?:
    | T
    | {
        type?: T;
        code?: T;
        label?: T;
        qty?: T;
        id?: T;
      };
  referenceImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  generatedQuote?: T;
  designerMockup?: T;
  rawPayload?: T;
  processingError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs_select".
 */
export interface EmailLogsSelect<T extends boolean = true> {
  title?: T;
  emailType?: T;
  status?: T;
  sentAt?: T;
  clientName?: T;
  to?: T;
  subject?: T;
  inquiry?: T;
  attachment?: T;
  html?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncCatalog".
 */
export interface TaskSyncCatalog {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskProcessInquiry".
 */
export interface TaskProcessInquiry {
  input: {
    inquiryId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}